"""Доменное ядро vtelemax.

В ядре размещается логика, общая для всех мессенджеров:

1. Правила валидации и нормализации.
2. Сценарии идентификации и регистрации.
3. Use-case операции, не зависящие от SDK платформ.
"""

from .errors import IdentityConflictError
from .guest_content import (
    BUTTON_ACCEPT_RULES,
    BUTTON_ABOUT,
    BUTTON_BALANCE,
    BUTTON_DOCS_LINK,
    BUTTON_HELP,
    BUTTON_MAIN_MENU,
    BUTTON_MY_TICKETS,
    BUTTON_PROFILE,
    BUTTON_SEND_PHONE,
    BUTTON_SUPPORT,
    BUTTON_SUPPORT_CONTACTS,
    BUTTON_SUPPORT_FEEDBACK,
    BUTTON_SUPPORT_QUESTION,
    BUTTON_VACANCIES,
    BUTTON_VIRTUAL_CARD,
    build_about_screen,
    build_balance_screen,
    build_legacy_upgrade_screen,
    build_help_screen,
    build_main_menu_screen,
    build_profile_not_found_screen,
    build_profile_screen,
    build_start_contact_screen,
    build_start_rules_screen,
    build_support_contacts_screen,
    build_support_feedback_screen,
    build_support_menu_screen,
    build_support_question_screen,
    build_vacancies_screen,
    normalize_menu_text,
    resolve_guest_menu_action,
)
from .onboarding import OnboardingFlowService, OnboardingState, OnboardingTransition
from .identity import StrictIdentityService
from .in_memory_identity_repository import InMemoryIdentityRepository
from .in_memory_support_repository import InMemorySupportRepository
from .loyalty_ports import (
    LoyaltyCard,
    LoyaltyCustomer,
    LoyaltyGateway,
    LoyaltyGatewayError,
    LoyaltyIssueCardResult,
    LoyaltyRegisterCustomerResult,
)
from .loyalty_use_cases import (
    GetLoyaltyBalanceUseCase,
    GetVirtualCardUseCase,
    LoyaltyMenuResult,
)
from .menu_contract import GuestMenuAction, MenuButtonContract, MenuScreenContract
from .models import Person, PlatformAccount, PlatformName, SUPPORTED_PLATFORMS
from .phone import normalize_phone
from .ports import IdentityRepository, IdentityUnitOfWork
from .support_models import (
    SupportDeliveryStatus,
    SupportMessage,
    SupportMessageAuthor,
    SupportTicket,
    SupportTicketStatus,
)
from .support_ports import SupportRepository, SupportUnitOfWork
from .support_use_cases import (
    CreateSupportTicketCommand,
    CreateSupportTicketTransactionalUseCase,
    CreatedSupportTicketResult,
    GetSupportTicketDetailsTransactionalUseCase,
    ListOpenSupportTicketsTransactionalUseCase,
    ListPersonSupportTicketsTransactionalUseCase,
    PullPendingModeratorMessagesTransactionalUseCase,
    ModeratorReplyCommand,
    ModeratorReplyRoutingResult,
    OpenSupportTicketSummary,
    PersonSupportTicketSummary,
    PendingModeratorDelivery,
    RouteModeratorReplyTransactionalUseCase,
    SupportTicketDetails,
    UpdateModeratorMessageDeliveryStatusCommand,
    UpdateModeratorMessageDeliveryStatusTransactionalUseCase,
)
from .use_cases import (
    GetPersonByAccountCommand,
    GetPersonByAccountTransactionalUseCase,
    GetPersonByAccountUseCase,
    RegisterOrAttachAccountCommand,
    RegisterOrAttachAccountTransactionalUseCase,
    RegisterOrAttachAccountUseCase,
)

__all__ = [
    "IdentityConflictError",
    "IdentityRepository",
    "IdentityUnitOfWork",
    "SupportRepository",
    "SupportUnitOfWork",
    "InMemoryIdentityRepository",
    "InMemorySupportRepository",
    "LoyaltyGateway",
    "LoyaltyGatewayError",
    "LoyaltyCard",
    "LoyaltyCustomer",
    "LoyaltyRegisterCustomerResult",
    "LoyaltyIssueCardResult",
    "GetLoyaltyBalanceUseCase",
    "GetVirtualCardUseCase",
    "LoyaltyMenuResult",
    "GuestMenuAction",
    "MenuButtonContract",
    "MenuScreenContract",
    "Person",
    "PlatformAccount",
    "PlatformName",
    "SUPPORTED_PLATFORMS",
    "GetPersonByAccountCommand",
    "GetPersonByAccountUseCase",
    "GetPersonByAccountTransactionalUseCase",
    "RegisterOrAttachAccountCommand",
    "RegisterOrAttachAccountTransactionalUseCase",
    "RegisterOrAttachAccountUseCase",
    "BUTTON_ABOUT",
    "BUTTON_ACCEPT_RULES",
    "BUTTON_BALANCE",
    "BUTTON_DOCS_LINK",
    "BUTTON_HELP",
    "BUTTON_MAIN_MENU",
    "BUTTON_MY_TICKETS",
    "BUTTON_PROFILE",
    "BUTTON_SEND_PHONE",
    "BUTTON_SUPPORT",
    "BUTTON_SUPPORT_CONTACTS",
    "BUTTON_SUPPORT_FEEDBACK",
    "BUTTON_SUPPORT_QUESTION",
    "BUTTON_VACANCIES",
    "BUTTON_VIRTUAL_CARD",
    "build_about_screen",
    "build_balance_screen",
    "build_help_screen",
    "build_legacy_upgrade_screen",
    "build_main_menu_screen",
    "build_profile_not_found_screen",
    "build_profile_screen",
    "build_start_contact_screen",
    "build_start_rules_screen",
    "build_support_contacts_screen",
    "build_support_feedback_screen",
    "build_support_menu_screen",
    "build_support_question_screen",
    "build_vacancies_screen",
    "normalize_menu_text",
    "resolve_guest_menu_action",
    "StrictIdentityService",
    "normalize_phone",
    "OnboardingFlowService",
    "OnboardingState",
    "OnboardingTransition",
    "SupportTicketStatus",
    "SupportMessageAuthor",
    "SupportDeliveryStatus",
    "SupportTicket",
    "SupportMessage",
    "CreateSupportTicketCommand",
    "CreatedSupportTicketResult",
    "CreateSupportTicketTransactionalUseCase",
    "ModeratorReplyCommand",
    "ModeratorReplyRoutingResult",
    "RouteModeratorReplyTransactionalUseCase",
    "SupportTicketDetails",
    "GetSupportTicketDetailsTransactionalUseCase",
    "OpenSupportTicketSummary",
    "ListOpenSupportTicketsTransactionalUseCase",
    "PersonSupportTicketSummary",
    "ListPersonSupportTicketsTransactionalUseCase",
    "PendingModeratorDelivery",
    "PullPendingModeratorMessagesTransactionalUseCase",
    "UpdateModeratorMessageDeliveryStatusCommand",
    "UpdateModeratorMessageDeliveryStatusTransactionalUseCase",
]
